//
//  Constants.swift
//  Blackjack
//
//  Created by Радэль Зубаиров on 22.12.2024.
//

enum Constants {
    static let menuCardsPng = "menuCardsPng"
    static let clubsCards: [CardModel] = [CardModel(suit: .clubs, value: 2, cardImage: "2_of_clubs", cardValue: .num2), CardModel(suit: .clubs, value: 3, cardImage: "3_of_clubs", cardValue: .num3), CardModel(suit: .clubs, value: 4, cardImage: "4_of_clubs", cardValue: .num4), CardModel(suit: .clubs, value: 5, cardImage: "5_of_clubs", cardValue: .num5), CardModel(suit: .clubs, value: 6, cardImage: "6_of_clubs", cardValue: .num6), CardModel(suit: .clubs, value: 7, cardImage: "7_of_clubs", cardValue: .num7), CardModel(suit: .clubs, value: 8, cardImage: "8_of_clubs", cardValue: .num8), CardModel(suit: .clubs, value: 9, cardImage: "9_of_clubs", cardValue: .num9), CardModel(suit: .clubs, value: 10, cardImage: "10_of_clubs", cardValue: .num10), CardModel(suit: .clubs, value: 10, cardImage: "jack_of_clubs", cardValue: .numJ), CardModel(suit: .clubs, value: 10, cardImage: "queen_of_clubs", cardValue: .numQ), CardModel(suit: .clubs, value: 10, cardImage: "king_of_clubs", cardValue: .numK), CardModel(suit: .clubs, value: 11, cardImage: "ace_of_clubs", cardValue: .numA)]
    static let diamondsCards : [CardModel] = [CardModel(suit: .diamonds, value: 2, cardImage: "2_of_diamonds", cardValue: .num2), CardModel(suit: .diamonds, value: 3, cardImage: "3_of_diamonds", cardValue: .num3), CardModel(suit: .diamonds, value: 4, cardImage: "4_of_diamonds", cardValue: .num4), CardModel(suit: .diamonds, value: 5, cardImage: "5_of_diamonds", cardValue: .num5), CardModel(suit: .diamonds, value: 6, cardImage: "6_of_diamonds", cardValue: .num6), CardModel(suit: .diamonds, value: 7, cardImage: "7_of_diamonds", cardValue: .num7), CardModel(suit: .diamonds, value: 8, cardImage: "8_of_diamonds", cardValue: .num8), CardModel(suit: .diamonds, value: 9, cardImage: "9_of_diamonds", cardValue: .num9), CardModel(suit: .diamonds, value: 10, cardImage: "10_of_diamonds", cardValue: .num10), CardModel(suit: .diamonds, value: 10, cardImage: "jack_of_diamonds", cardValue: .numJ), CardModel(suit: .diamonds, value: 10, cardImage: "queen_of_diamonds", cardValue: .numQ), CardModel(suit: .diamonds, value: 10, cardImage: "king_of_diamonds", cardValue: .numK), CardModel(suit: .diamonds, value: 11, cardImage: "ace_of_diamonds", cardValue: .numA)]
    static let heartsCards : [CardModel] = [CardModel(suit: .hearts, value: 2, cardImage: "2_of_hearts", cardValue: .num2), CardModel(suit: .hearts, value: 3, cardImage: "3_of_hearts", cardValue: .num3), CardModel(suit: .hearts, value: 4, cardImage: "4_of_hearts", cardValue: .num4), CardModel(suit: .hearts, value: 5, cardImage: "5_of_hearts", cardValue: .num5), CardModel(suit: .hearts, value: 6, cardImage: "6_of_hearts", cardValue: .num6), CardModel(suit: .hearts, value: 7, cardImage: "7_of_hearts", cardValue: .num7), CardModel(suit: .hearts, value: 8, cardImage: "8_of_hearts", cardValue: .num8), CardModel(suit: .hearts, value: 9, cardImage: "9_of_hearts", cardValue: .num9), CardModel(suit: .hearts, value: 10, cardImage: "10_of_hearts", cardValue: .num10), CardModel(suit: .hearts, value: 10, cardImage: "jack_of_hearts", cardValue: .numJ), CardModel(suit: .hearts, value: 10, cardImage: "queen_of_hearts", cardValue: .numQ), CardModel(suit: .hearts, value: 10, cardImage: "king_of_hearts", cardValue: .numK), CardModel(suit: .hearts, value: 11, cardImage: "ace_of_hearts", cardValue: .numA)]
    static let spadesCards : [CardModel] = [CardModel(suit: .spades, value: 2, cardImage: "2_of_spades", cardValue: .num2), CardModel(suit: .spades, value: 3, cardImage: "3_of_spades", cardValue: .num3), CardModel(suit: .spades, value: 4, cardImage: "4_of_spades", cardValue: .num4), CardModel(suit: .spades, value: 5, cardImage: "5_of_spades", cardValue: .num5), CardModel(suit: .spades, value: 6, cardImage: "6_of_spades", cardValue: .num6), CardModel(suit: .spades, value: 7, cardImage: "7_of_spades", cardValue: .num7), CardModel(suit: .spades, value: 8, cardImage: "8_of_spades", cardValue: .num8), CardModel(suit: .spades, value: 9, cardImage: "9_of_spades", cardValue: .num9), CardModel(suit: .spades, value: 10, cardImage: "10_of_spades", cardValue: .num10), CardModel(suit: .spades, value: 10, cardImage: "jack_of_spades", cardValue: .numJ), CardModel(suit: .spades, value: 10, cardImage: "queen_of_spades", cardValue: .numQ), CardModel(suit: .spades, value: 10, cardImage: "king_of_spades", cardValue: .numK), CardModel(suit: .spades, value: 11, cardImage: "ace_of_spades", cardValue: .numA)]
    static let jokersCards = ["red_joker", "black_joker"]
    static let allCards = clubsCards + diamondsCards + heartsCards + spadesCards
}
